In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import obspy
from hydrophone_data_processing import load

In [2]:
df = load.import_detections('/media/sda/data/borehole/detections/*.csv')

In [6]:
df.reset_index()

    index                         time  similarity  template_id
0       0  2019-05-23T09:50:08.937000Z    0.878120            0
1       0  2019-05-27T14:01:42.332000Z    0.896187            0
2       0  2019-06-05T19:22:09.245999Z    0.845635            0
3       0  2019-05-25T14:52:00.309000Z    0.832567            0
4       0  2019-06-03T09:33:05.746000Z    0.803248            0
5       0  2019-05-06T01:07:42.741000Z    0.804644            0
6       1  2019-05-06T01:12:03.352000Z    0.806152            0
7       2  2019-05-06T01:13:41.044000Z    0.871673            0
8       3  2019-05-06T01:14:03.443000Z    0.822991            0
9       4  2019-05-06T08:00:38.684000Z    0.844727            0
10      5  2019-05-06T08:01:44.606000Z    0.890552            0
11      6  2019-05-06T22:39:35.278000Z    0.878664            0
12      0  2019-05-30T03:05:21.896000Z    0.823386            0
13      0  2019-05-05T07:05:49.813000Z    0.853986            0
14      1  2019-05-05T19:34:37.970000Z    0.923814            0
15      2  2019-05-05T19:37:58.637000Z    0.895130            0
16      3  2019-05-05T19:41:35.191000Z    0.835545            0
17      0  2019-05-21T07:03:27.495000Z    0.812786            0
18      1  2019-05-21T07:04:18.850000Z    1.000000            0
19      0  2019-05-02T08:34:05.219999Z    0.879116            0
20      1  2019-05-02T08:34:56.173999Z    0.850827            0
21      2  2019-05-02T10:27:54.056999Z    0.860519            0
22      3  2019-05-02T12:08:43.894999Z    0.906010            0
23      4  2019-05-02T12:09:15.602999Z    0.814478            0
24      5  2019-05-02T13:53:54.702999Z    0.827825            0
25      0  2019-05-10T03:23:01.214000Z    0.861089            0
26      1  2019-05-10T03:27:58.265000Z    0.815340            0
27      2  2019-05-10T03:30:37.634000Z    0.838345            0
28      3  2019-05-10T03:31:44.294000Z    0.918499            0
29      0  2019-05-07T11:46:19.699000Z    0.856064            0

In [4]:
# import glob

In [5]:
# glob.glob('/media/sda/data/borehole/detections/*.csv')